### PR TITLE
Image File Compression

### PR DESCRIPTION
**Pull request by Peppernrino**
Ran a series of lossless compression algorithms to make the images smaller. Total reduction of 71,615 bytes. :)

### CODE REVIEW

**Comment by cuibonobo** [comment]
It might be useful to document how these images were compressed so this can be recreated in the future. 👀

**Comment by Peppernrino** [comment]
Here's an example of what kinds of programs I just ran on a file in the propaganda repo:

* PngOptimizer.exe -file:"Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* truepng.exe -o4 -tz -md remove all -g0 /i0 /tz /quiet /y /out "Wide_rectangular_peoplesopen.net_sticker_less_text.png" "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* pngout.exe /q /y /r /d0 /mincodes0 /kacTL,fcTL,fdAT /s0 "Wide_rectangular_peoplesopen.net_sticker_less_text.png" "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* ptipng.exe -zw32k -quiet -o6 -strip all "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* leanify.exe -q -i 30 "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* pngwolf.exe --out-deflate=zopfli,iter=30 --in="Wide_rectangular_peoplesopen.net_sticker_less_text.png" --out="Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* pngrewrite.exe "Wide_rectangular_peoplesopen.net_sticker_less_text.png" "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* advpng.exe -z -q -4 -i 30 "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* ECT.exe -quiet --allfilters -strip -9 "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* pingo.exe -s8 "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* deflopt.exe /a /b /s "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* defluff.bat "Wide_rectangular_peoplesopen.net_sticker_less_text.png" "Wide_rectangular_peoplesopen.net_sticker_less_text.png"
* deflopt.exe /a /b /s "Wide_rectangular_peoplesopen.net_sticker_less_text.png"

I removed my directory information. :)

**Comment by Peppernrino** [comment]
lol... I forgot it would drop mentions in here every time I mentioned the pull. Gonna make a pastebin for it now. :P

**Comment by paidforby** [comment]
These images aren't really that crucial to anything being actively developed, but I guess it doesn't hurt to have them losslessly compressed. Going to merge this just to clean up the PRs. Thanks for contributing.

**Pull request merged**
