### PR TITLE
ESP32 TTGO

### PR DESCRIPTION
**Pull request by paidforby**
Merging in the fixes to esp32 fork provided by @libbymiller 
I was **finally** able to test this fork on the suggested ESP32 TTGO dev board (available from various retailers such as [AliExpress](https://www.aliexpress.com/item/4000061163947.html?src=google&src=google&albch=shopping&acnt=494-037-6276&isdl=y&slnk=&plac=&mtctp=&albbt=Google_7_shopping&aff_platform=google&aff_short_key=UneMJZVf&&albagn=888888&albcp=1582410664&albag=59754279756&trgt=539263010115&crea=en4000061163947&netw=u&device=c&gclid=Cj0KCQiAtf_tBRDtARIsAIbAKe2qAzHxri1-mOkqsZ83CWfRMi79oKpuFM5X-fWX2LfwPfH3kjcVPQUaAl_EEALw_wcB&gclsrc=aw.ds) and [Banggood](https://www.banggood.com/LILYGO-TTGO-T-Display-ESP32-CP2104-WiFi-bluetooth-Module-1_14-Inch-LCD-Development-Board-For-Arduino-p-1522925.html?gmcCountry=US&currency=USD&createTmp=1&utm_source=googleshopping&utm_medium=cpc_bgs&utm_content=frank&utm_campaign=ssc-us-all-newcustom-0921&ad_id=384148714739&gclid=Cj0KCQiAtf_tBRDtARIsAIbAKe1Rliw_6JLu1uk4LAt56hI3EQLEPZQE8TxwhRWCIx-WV-FB5Z8FeYIaAmG0EALw_wcB&cur_warehouse=CN))

Things that have been tested and are working,
* firmware compiles and flashes to the TTGO dev board
* webapp compiles and flashes it to the TTGO dev board file system
* able to connect to wifi network created by TTGO dev board and can connect to webapp at 192.148.4.1
* websocket communication between webapp and firmware appears to be functioning (I can see messages from webapp in screen session)

Things that aren't working,
* mac address is blank, this is a simple fix, the call to `WiFi.mode(WIFI_AP);` at [line 309 of firmware.ino](https://github.com/libbymiller/disaster-radio/blob/esp32/firmware/firmware.ino#L309) needs to be moved ahead of the call to `WiFi.macAddress(mac);` at line 304.
* messages are not being sent over LoRa transceiver. i.e. two TTGO boards cannot send/receive messages. I need to review pin assignments and debug some of the logic, may be a bug I already fixed in main (ESP8266) branch.

Things I haven't tested,
* SD card functionality has not been tested (and will not be tested by me personally any time soon)
* since no SD card yet, the map tile application has not been tested either.
* routing appears to be running, I'm planning more

Next steps, are to sync up this branch with the commits made after it was branched from master. Then, I can possibly finish restructuring the routing protocol code so that is more portable between the simulator and the ESP8266 and the ESP32. Work on this is currently stored in my fork of the simulator https://github.com/paidforby/disaster-radio-simulator/tree/master/routers

I'm not sure of the current state of the hardware prototype. FYI @Juul and @fitzdoingprojects any work related to an ESP32 prototype should be added to this branch until we decide on way to possibly merge this into master.

### CODE REVIEW

**Comment by Juul** [comment]
Awesome! This is really great! We're starting Monday disaster.radio evenings back up. Maybe you can call in one of these days and we can sync? My goal for this week is to merge in my own patch set that improves on the websocket communication.

**Comment by libbymiller** [comment]
Thank you! I'd intended to do a PR but not got to it. I have three devices to test here.

**Comment by paidforby** [comment]
Great, merging now. I may be actively making changes to this branch to sync it with master, so make sure to pull in any new commits.

**Comment by samuk** [comment]
Great stuff! Can we just confirm we're all working with the V2.1_1.6 version of the board?

I believe the previous versions all had different LoRa pins.

This is what I have:
https://www.aliexpress.com/item/32915894264.html?spm=a2g0o.productlist.0.0.671054bdhI1Hix&algo_pvid=aec249fc-c80a-4c81-8220-334dc9f635b1&algo_expid=aec249fc-c80a-4c81-8220-334dc9f635b1-0&btsid=6d976d5a-e661-47f6-b371-7f0bc42c5336&ws_ab_test=searchweb0_0,searchweb201602_7,searchweb201603_55

**Comment by paidforby** [comment]
Can confirm that I am using the same model pictured in the link provided by @samuk which reads `T3_V1.6 20180606`
I linked to the the "wrong" board in the PR.

**Comment by Juul** [comment]
Also please be aware that some of the TTGO circuit diagrams from their
github do not match the actual boards (according to Fitz).

**Comment by paidforby** [comment]
Yes, I've read that a few places. I have the LoRa transceiver working with this commit ed76028449e44b3adc2c50b5d35d57f431a8b62e looks like there was confusion around the irq and DIO pins. I will eventually document all pins being used in the README.

Also, I almost have two TTGO boards communicating, have to write an incoming packet buffer to avoid a memory leak caused by sending to the websocket server inside of the onReceive callback.

**Pull request merged**
